package main

import (
	"github.com/gin-gonic/gin"
	// docs is generated by Swag CLI, you have to import it.
)

func setupRouter() *gin.Engine {

	r := gin.Default()

	r.GET("/pingas", func(c *gin.Context) {
		c.String(200, "pong")
	})

	return r
}

func main() {

	r := setupRouter()

	r.Run(":8080")
}
